spring.application.name=disfraces-rivera

server.port=8080

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/disfraces_rivera?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=disfraces_user
spring.datasource.password=Disfraces123*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Archivos subidos
app.upload.dir=uploads/disfraces
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Internacionalización
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Correo Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leslicita2675@gmail.com
spring.mail.password=crpawdswzeywoylh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Correo del administrador que recibirá las reservas
app.admin.email=leslicita2675@gmail.com
